import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# RetinaGuard V500: Primary Classifier Training\n",
                "This notebook contains the source code for training the baseline Deep Learning Convolutional Neural Network (CNN) used to detect Retinitis Pigmentosa.\n",
                "Because of data scarcity, this training pipeline utilizes both real clinical images and synthetic images generated by our WGAN."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {},
            "execution_count": 1,
            "outputs": [],
            "source": [
                "import tensorflow as tf\n",
                "from tensorflow.keras.models import Sequential\n",
                "from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout\n",
                "from tensorflow.keras.preprocessing.image import ImageDataGenerator\n",
                "from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping\n",
                "import matplotlib.pyplot as plt\n",
                "import numpy as np"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 1. Data Preprocessing & Augmentation\n",
                "We use `ImageDataGenerator` to load the dataset and apply data augmentation to prevent overfitting."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {},
            "execution_count": 2,
            "outputs": [],
            "source": [
                "IMG_SIZE = (224, 224)\n",
                "BATCH_SIZE = 32\n",
                "\n",
                "# Data Augmentation\n",
                "train_datagen = ImageDataGenerator(\n",
                "    rescale=1./255,\n",
                "    rotation_range=20,\n",
                "    zoom_range=0.15,\n",
                "    width_shift_range=0.2,\n",
                "    height_shift_range=0.2,\n",
                "    horizontal_flip=True,\n",
                "    validation_split=0.2\n",
                ")\n",
                "\n",
                "train_generator = train_datagen.flow_from_directory(\n",
                "    'Dataset/Final_RP_and_Healthy',\n",
                "    target_size=IMG_SIZE,\n",
                "    batch_size=BATCH_SIZE,\n",
                "    class_mode='binary',\n",
                "    subset='training'\n",
                ")\n",
                "\n",
                "validation_generator = train_datagen.flow_from_directory(\n",
                "    'Dataset/Final_RP_and_Healthy',\n",
                "    target_size=IMG_SIZE,\n",
                "    batch_size=BATCH_SIZE,\n",
                "    class_mode='binary',\n",
                "    subset='validation'\n",
                ")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 2. Deep Learning Architecture (CNN)\n",
                "We construct a custom CNN designed to detect spatial anomalies and texture degradation associated with Retinitis Pigmentosa."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {},
            "execution_count": 3,
            "outputs": [],
            "source": [
                "def build_classifier():\n",
                "    model = Sequential([\n",
                "        # Convolutional Block 1\n",
                "        Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),\n",
                "        MaxPooling2D(2, 2),\n",
                "        \n",
                "        # Convolutional Block 2\n",
                "        Conv2D(64, (3, 3), activation='relu'),\n",
                "        MaxPooling2D(2, 2),\n",
                "        \n",
                "        # Convolutional Block 3\n",
                "        Conv2D(128, (3, 3), activation='relu'),\n",
                "        MaxPooling2D(2, 2),\n",
                "        \n",
                "        # Flatten & Dense Reasoning Layers\n",
                "        Flatten(),\n",
                "        Dense(128, activation='relu'),\n",
                "        Dropout(0.5), # Prevent overfitting\n",
                "        \n",
                "        # Final Binary Output (Healthy vs RP)\n",
                "        Dense(1, activation='sigmoid')\n",
                "    ])\n",
                "    return model\n",
                "\n",
                "model = build_classifier()\n",
                "model.summary()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 3. Compilation & Callbacks\n",
                "We use the Adam optimizer and Binary Crossentropy loss. We also set up a ModelCheckpoint to save the `.h5` file with the best validation accuracy."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {},
            "execution_count": 4,
            "outputs": [],
            "source": [
                "model.compile(\n",
                "    optimizer='adam',\n",
                "    loss='binary_crossentropy',\n",
                "    metrics=['accuracy']\n",
                ")\n",
                "\n",
                "# Save the best model during training\n",
                "checkpoint = ModelCheckpoint(\n",
                "    'RetinaGuard_Clinical_Balanced.h5',\n",
                "    monitor='val_accuracy',\n",
                "    save_best_only=True,\n",
                "    mode='max',\n",
                "    verbose=1\n",
                ")\n",
                "\n",
                "# Stop training if it stops improving\n",
                "early_stopping = EarlyStopping(monitor='val_loss', patience=5)\n",
                "\n",
                "callbacks_list = [checkpoint, early_stopping]"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 4. Training the Model\n",
                "Executing the training loop."
            ]
        },
        {
            "cell_type": "code",
            "metadata": {},
            "execution_count": 5,
            "outputs": [],
            "source": [
                "EPOCHS = 25\n",
                "\n",
                "history = model.fit(\n",
                "    train_generator,\n",
                "    validation_data=validation_generator,\n",
                "    epochs=EPOCHS,\n",
                "    callbacks=callbacks_list\n",
                ")\n",
                "\n",
                "print(\"Training Complete! Best model saved as RetinaGuard_Clinical_Balanced.h5\")"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.11.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open("models/Classifier_Training.ipynb", "w") as f:
    json.dump(notebook, f, indent=4)
print("Notebook generated successfully!")
